### ISSUE TITLE
Explore Screen: New Density Readout Panel

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy-basics#6]
From #4 Here is the screenshot from the design doc:

https://docs.google.com/document/d/1XH0LhgFuor4dfc0gfF96Ao-qk7771vRLn53jQplDe0I/edit

![image](https://github.com/phetsims/buoyancy-basics/assets/6856943/683bc8bc-9635-433f-80f8-d111895a49dd)

**Comment by DianaTavares** [comment]
In the design meeting we agree in some changes for the density readout. 

For **Density Simulation** (probably these issue should be in common code?), the readout will change the small arrows for a big tip (like triangles). And Taliesin suggested that only colors is not enough for distinguish for some students, then also suggested to add the letter.

This is the new design:
![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/a2e9a698-900d-487b-a275-693431b45fb4)

For **Buoyancy: Basics** we need to have the levels to the left of the panel because we have the values of A and B in the same orientation, then in some scenarios the labels are going to overlap. This is the new design:
![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/d6adc6d0-59c5-49f4-bfa9-33720cd510be)


For the mystery material, the density readout of the block needs to be hidden:
![image](https://github.com/phetsims/buoyancy-basics/assets/26031501/56b1b79d-ff19-42ae-9498-3ca8ae832cb8)

**Comment by AgustinVallejo** [comment]
Discussed with @DianaTavares. Main items:

- Legend can stay as 'A: 200...' without the Block part. Teachers will decide in the interviews.
- We should add maxWidth on individual material labels.
- Panel width is allowed to use up all the horizontal space according to translations
- Center the panel if the space allows, otherwise move if it's going to overlap with other panels; respect the margins.

**Comment by zepumph** [comment]
- [x] We don't want to show the readout when it is a mystery material. Instead show a "?".

**Comment by AgustinVallejo** [comment]
Approved by @DianaTavares
